{
  "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
  "version": "2.1.0",
  "runs": [
    {
      "tool": {
        "driver": {
          "name": "CodeScoring",
          "informationUri": "https://codescoring.ru/",
          "fullName": "CodeScoring Software Composition Analysis",
          "version": "2024.5.0",
          "rules": [
            {
              "id": "[7.5 High] [9.8 Critical] CVE-2022-28346",
              "shortDescription": {
                "text": "CVE-2022-28346 Package: pkg:pypi/django@3.0.7"
              },
              "help": {
                "text": "Vulnerability CVE-2022-28346\nCVSSv2: 7.5 High\nCVSSv3: 9.8 Critical\nPackage: pkg:pypi/django@3.0.7\nFixed Version: \n",
                "markdown": "**Vulnerability CVE-2022-28346**\n| CVSSv2 | CVSSv3 | Package | Fixed Version |\n| --- | --- | --- | --- |\n|7.5 High|9.8 Critical|pkg:pypi/django@3.0.7||\n"
              },
              "properties": {
                "tags": [
                  "vulnerability",
                  "[7.5 High] [9.8 Critical]",
                  "pkg:pypi/django@3.0.7"
                ],
                "precision": "very-high"
              }
            },
            {
              "id": "[7.5 High] [9.8 Critical] CVE-2022-28347",
              "shortDescription": {
                "text": "CVE-2022-28347 Package: pkg:pypi/django@3.0.7"
              },
              "help": {
                "text": "Vulnerability CVE-2022-28347\nCVSSv2: 7.5 High\nCVSSv3: 9.8 Critical\nPackage: pkg:pypi/django@3.0.7\nFixed Version: \n",
                "markdown": "**Vulnerability CVE-2022-28347**\n| CVSSv2 | CVSSv3 | Package | Fixed Version |\n| --- | --- | --- | --- |\n|7.5 High|9.8 Critical|pkg:pypi/django@3.0.7||\n"
              },
              "properties": {
                "tags": [
                  "vulnerability",
                  "[7.5 High] [9.8 Critical]",
                  "pkg:pypi/django@3.0.7"
                ],
                "precision": "very-high"
              }
            },
            {
              "id": "[7.5 High] [9.8 Critical] CVE-2021-35042",
              "shortDescription": {
                "text": "CVE-2021-35042 Package: pkg:pypi/django@3.0.7"
              },
              "help": {
                "text": "Vulnerability CVE-2021-35042\nCVSSv2: 7.5 High\nCVSSv3: 9.8 Critical\nPackage: pkg:pypi/django@3.0.7\nFixed Version: 3.1.13\n",
                "markdown": "**Vulnerability CVE-2021-35042**\n| CVSSv2 | CVSSv3 | Package | Fixed Version |\n| --- | --- | --- | --- |\n|7.5 High|9.8 Critical|pkg:pypi/django@3.0.7|3.1.13|\n"
              },
              "properties": {
                "tags": [
                  "vulnerability",
                  "[7.5 High] [9.8 Critical]",
                  "pkg:pypi/django@3.0.7"
                ],
                "precision": "very-high"
              }
            },
            {
              "id": "[7.5 High] [9.8 Critical] CVE-2022-34265",
              "shortDescription": {
                "text": "CVE-2022-34265 Package: pkg:pypi/django@3.0.7"
              },
              "help": {
                "text": "Vulnerability CVE-2022-34265\nCVSSv2: 7.5 High\nCVSSv3: 9.8 Critical\nPackage: pkg:pypi/django@3.0.7\nFixed Version: \n",
                "markdown": "**Vulnerability CVE-2022-34265**\n| CVSSv2 | CVSSv3 | Package | Fixed Version |\n| --- | --- | --- | --- |\n|7.5 High|9.8 Critical|pkg:pypi/django@3.0.7||\n"
              },
              "properties": {
                "tags": [
                  "vulnerability",
                  "[7.5 High] [9.8 Critical]",
                  "pkg:pypi/django@3.0.7"
                ],
                "precision": "very-high"
              }
            },
            {
              "id": "[None] [9.8 Critical] CVE-2023-31047",
              "shortDescription": {
                "text": "CVE-2023-31047 Package: pkg:pypi/django@3.0.7"
              },
              "help": {
                "text": "Vulnerability CVE-2023-31047\nCVSSv2: None\nCVSSv3: 9.8 Critical\nPackage: pkg:pypi/django@3.0.7\nFixed Version: \n",
                "markdown": "**Vulnerability CVE-2023-31047**\n| CVSSv2 | CVSSv3 | Package | Fixed Version |\n| --- | --- | --- | --- |\n|None|9.8 Critical|pkg:pypi/django@3.0.7||\n"
              },
              "properties": {
                "tags": [
                  "vulnerability",
                  "[None] [9.8 Critical]",
                  "pkg:pypi/django@3.0.7"
                ],
                "precision": "very-high"
              }
            },
            {
              "id": "[None] [8.8 High] CVE-2022-36359",
              "shortDescription": {
                "text": "CVE-2022-36359 Package: pkg:pypi/django@3.0.7"
              },
              "help": {
                "text": "Vulnerability CVE-2022-36359\nCVSSv2: None\nCVSSv3: 8.8 High\nPackage: pkg:pypi/django@3.0.7\nFixed Version: \n",
                "markdown": "**Vulnerability CVE-2022-36359**\n| CVSSv2 | CVSSv3 | Package | Fixed Version |\n| --- | --- | --- | --- |\n|None|8.8 High|pkg:pypi/django@3.0.7||\n"
              },
              "properties": {
                "tags": [
                  "vulnerability",
                  "[None] [8.8 High]",
                  "pkg:pypi/django@3.0.7"
                ],
                "precision": "very-high"
              }
            },
            {
              "id": "[5.0 Medium] [7.5 High] CVE-2020-29651",
              "shortDescription": {
                "text": "CVE-2020-29651 Package: pkg:pypi/py@1.9"
              },
              "help": {
                "text": "Vulnerability CVE-2020-29651\nCVSSv2: 5.0 Medium\nCVSSv3: 7.5 High\nPackage: pkg:pypi/py@1.9\nFixed Version: 1.10.0\n",
                "markdown": "**Vulnerability CVE-2020-29651**\n| CVSSv2 | CVSSv3 | Package | Fixed Version |\n| --- | --- | --- | --- |\n|5.0 Medium|7.5 High|pkg:pypi/py@1.9|1.10.0|\n"
              },
              "properties": {
                "tags": [
                  "vulnerability",
                  "[5.0 Medium] [7.5 High]",
                  "pkg:pypi/py@1.9"
                ],
                "precision": "very-high"
              }
            },
            {
              "id": "[5.0 Medium] [7.5 High] CVE-2020-24583",
              "shortDescription": {
                "text": "CVE-2020-24583 Package: pkg:pypi/django@3.0.7"
              },
              "help": {
                "text": "Vulnerability CVE-2020-24583\nCVSSv2: 5.0 Medium\nCVSSv3: 7.5 High\nPackage: pkg:pypi/django@3.0.7\nFixed Version: 3.0.10\n",
                "markdown": "**Vulnerability CVE-2020-24583**\n| CVSSv2 | CVSSv3 | Package | Fixed Version |\n| --- | --- | --- | --- |\n|5.0 Medium|7.5 High|pkg:pypi/django@3.0.7|3.0.10|\n"
              },
              "properties": {
                "tags": [
                  "vulnerability",
                  "[5.0 Medium] [7.5 High]",
                  "pkg:pypi/django@3.0.7"
                ],
                "precision": "very-high"
              }
            },
            {
              "id": "[5.0 Medium] [7.5 High] CVE-2020-24584",
              "shortDescription": {
                "text": "CVE-2020-24584 Package: pkg:pypi/django@3.0.7"
              },
              "help": {
                "text": "Vulnerability CVE-2020-24584\nCVSSv2: 5.0 Medium\nCVSSv3: 7.5 High\nPackage: pkg:pypi/django@3.0.7\nFixed Version: 3.0.10\n",
                "markdown": "**Vulnerability CVE-2020-24584**\n| CVSSv2 | CVSSv3 | Package | Fixed Version |\n| --- | --- | --- | --- |\n|5.0 Medium|7.5 High|pkg:pypi/django@3.0.7|3.0.10|\n"
              },
              "properties": {
                "tags": [
                  "vulnerability",
                  "[5.0 Medium] [7.5 High]",
                  "pkg:pypi/django@3.0.7"
                ],
                "precision": "very-high"
              }
            },
            {
              "id": "[5.0 Medium] [7.5 High] CVE-2021-33571",
              "shortDescription": {
                "text": "CVE-2021-33571 Package: pkg:pypi/django@3.0.7"
              },
              "help": {
                "text": "Vulnerability CVE-2021-33571\nCVSSv2: 5.0 Medium\nCVSSv3: 7.5 High\nPackage: pkg:pypi/django@3.0.7\nFixed Version: 3.1.12\n",
                "markdown": "**Vulnerability CVE-2021-33571**\n| CVSSv2 | CVSSv3 | Package | Fixed Version |\n| --- | --- | --- | --- |\n|5.0 Medium|7.5 High|pkg:pypi/django@3.0.7|3.1.12|\n"
              },
              "properties": {
                "tags": [
                  "vulnerability",
                  "[5.0 Medium] [7.5 High]",
                  "pkg:pypi/django@3.0.7"
                ],
                "precision": "very-high"
              }
            },
            {
              "id": "[5.0 Medium] [7.5 High] CVE-2021-31542",
              "shortDescription": {
                "text": "CVE-2021-31542 Package: pkg:pypi/django@3.0.7"
              },
              "help": {
                "text": "Vulnerability CVE-2021-31542\nCVSSv2: 5.0 Medium\nCVSSv3: 7.5 High\nPackage: pkg:pypi/django@3.0.7\nFixed Version: 3.1.9\n",
                "markdown": "**Vulnerability CVE-2021-31542**\n| CVSSv2 | CVSSv3 | Package | Fixed Version |\n| --- | --- | --- | --- |\n|5.0 Medium|7.5 High|pkg:pypi/django@3.0.7|3.1.9|\n"
              },
              "properties": {
                "tags": [
                  "vulnerability",
                  "[5.0 Medium] [7.5 High]",
                  "pkg:pypi/django@3.0.7"
                ],
                "precision": "very-high"
              }
            },
            {
              "id": "[5.0 Medium] [7.5 High] CVE-2021-45115",
              "shortDescription": {
                "text": "CVE-2021-45115 Package: pkg:pypi/django@3.0.7"
              },
              "help": {
                "text": "Vulnerability CVE-2021-45115\nCVSSv2: 5.0 Medium\nCVSSv3: 7.5 High\nPackage: pkg:pypi/django@3.0.7\nFixed Version: \n",
                "markdown": "**Vulnerability CVE-2021-45115**\n| CVSSv2 | CVSSv3 | Package | Fixed Version |\n| --- | --- | --- | --- |\n|5.0 Medium|7.5 High|pkg:pypi/django@3.0.7||\n"
              },
              "properties": {
                "tags": [
                  "vulnerability",
                  "[5.0 Medium] [7.5 High]",
                  "pkg:pypi/django@3.0.7"
                ],
                "precision": "very-high"
              }
            },
            {
              "id": "[5.0 Medium] [7.5 High] CVE-2021-45116",
              "shortDescription": {
                "text": "CVE-2021-45116 Package: pkg:pypi/django@3.0.7"
              },
              "help": {
                "text": "Vulnerability CVE-2021-45116\nCVSSv2: 5.0 Medium\nCVSSv3: 7.5 High\nPackage: pkg:pypi/django@3.0.7\nFixed Version: \n",
                "markdown": "**Vulnerability CVE-2021-45116**\n| CVSSv2 | CVSSv3 | Package | Fixed Version |\n| --- | --- | --- | --- |\n|5.0 Medium|7.5 High|pkg:pypi/django@3.0.7||\n"
              },
              "properties": {
                "tags": [
                  "vulnerability",
                  "[5.0 Medium] [7.5 High]",
                  "pkg:pypi/django@3.0.7"
                ],
                "precision": "very-high"
              }
            },
            {
              "id": "[5.0 Medium] [7.5 High] CVE-2022-23833",
              "shortDescription": {
                "text": "CVE-2022-23833 Package: pkg:pypi/django@3.0.7"
              },
              "help": {
                "text": "Vulnerability CVE-2022-23833\nCVSSv2: 5.0 Medium\nCVSSv3: 7.5 High\nPackage: pkg:pypi/django@3.0.7\nFixed Version: \n",
                "markdown": "**Vulnerability CVE-2022-23833**\n| CVSSv2 | CVSSv3 | Package | Fixed Version |\n| --- | --- | --- | --- |\n|5.0 Medium|7.5 High|pkg:pypi/django@3.0.7||\n"
              },
              "properties": {
                "tags": [
                  "vulnerability",
                  "[5.0 Medium] [7.5 High]",
                  "pkg:pypi/django@3.0.7"
                ],
                "precision": "very-high"
              }
            },
            {
              "id": "[5.0 None] [7.5 High] CVE-2023-30608",
              "shortDescription": {
                "text": "CVE-2023-30608 Package: pkg:pypi/sqlparse@0.3.1"
              },
              "help": {
                "text": "Vulnerability CVE-2023-30608\nCVSSv2: 5.0 None\nCVSSv3: 7.5 High\nPackage: pkg:pypi/sqlparse@0.3.1\nFixed Version: 0.4.4\n",
                "markdown": "**Vulnerability CVE-2023-30608**\n| CVSSv2 | CVSSv3 | Package | Fixed Version |\n| --- | --- | --- | --- |\n|5.0 None|7.5 High|pkg:pypi/sqlparse@0.3.1|0.4.4|\n"
              },
              "properties": {
                "tags": [
                  "vulnerability",
                  "[5.0 None] [7.5 High]",
                  "pkg:pypi/sqlparse@0.3.1"
                ],
                "precision": "very-high"
              }
            },
            {
              "id": "[5.0 None] [7.5 High] CVE-2022-42969",
              "shortDescription": {
                "text": "CVE-2022-42969 Package: pkg:pypi/py@1.9"
              },
              "help": {
                "text": "Vulnerability CVE-2022-42969\nCVSSv2: 5.0 None\nCVSSv3: 7.5 High\nPackage: pkg:pypi/py@1.9\nFixed Version: \n",
                "markdown": "**Vulnerability CVE-2022-42969**\n| CVSSv2 | CVSSv3 | Package | Fixed Version |\n| --- | --- | --- | --- |\n|5.0 None|7.5 High|pkg:pypi/py@1.9||\n"
              },
              "properties": {
                "tags": [
                  "vulnerability",
                  "[5.0 None] [7.5 High]",
                  "pkg:pypi/py@1.9"
                ],
                "precision": "very-high"
              }
            },
            {
              "id": "[None] [7.5 High] CVE-2022-41323",
              "shortDescription": {
                "text": "CVE-2022-41323 Package: pkg:pypi/django@3.0.7"
              },
              "help": {
                "text": "Vulnerability CVE-2022-41323\nCVSSv2: None\nCVSSv3: 7.5 High\nPackage: pkg:pypi/django@3.0.7\nFixed Version: \n",
                "markdown": "**Vulnerability CVE-2022-41323**\n| CVSSv2 | CVSSv3 | Package | Fixed Version |\n| --- | --- | --- | --- |\n|None|7.5 High|pkg:pypi/django@3.0.7||\n"
              },
              "properties": {
                "tags": [
                  "vulnerability",
                  "[None] [7.5 High]",
                  "pkg:pypi/django@3.0.7"
                ],
                "precision": "very-high"
              }
            },
            {
              "id": "[None] [7.5 High] CVE-2023-23969",
              "shortDescription": {
                "text": "CVE-2023-23969 Package: pkg:pypi/django@3.0.7"
              },
              "help": {
                "text": "Vulnerability CVE-2023-23969\nCVSSv2: None\nCVSSv3: 7.5 High\nPackage: pkg:pypi/django@3.0.7\nFixed Version: \n",
                "markdown": "**Vulnerability CVE-2023-23969**\n| CVSSv2 | CVSSv3 | Package | Fixed Version |\n| --- | --- | --- | --- |\n|None|7.5 High|pkg:pypi/django@3.0.7||\n"
              },
              "properties": {
                "tags": [
                  "vulnerability",
                  "[None] [7.5 High]",
                  "pkg:pypi/django@3.0.7"
                ],
                "precision": "very-high"
              }
            },
            {
              "id": "[None] [7.5 High] CVE-2023-24580",
              "shortDescription": {
                "text": "CVE-2023-24580 Package: pkg:pypi/django@3.0.7"
              },
              "help": {
                "text": "Vulnerability CVE-2023-24580\nCVSSv2: None\nCVSSv3: 7.5 High\nPackage: pkg:pypi/django@3.0.7\nFixed Version: \n",
                "markdown": "**Vulnerability CVE-2023-24580**\n| CVSSv2 | CVSSv3 | Package | Fixed Version |\n| --- | --- | --- | --- |\n|None|7.5 High|pkg:pypi/django@3.0.7||\n"
              },
              "properties": {
                "tags": [
                  "vulnerability",
                  "[None] [7.5 High]",
                  "pkg:pypi/django@3.0.7"
                ],
                "precision": "very-high"
              }
            },
            {
              "id": "[None] [7.5 High] CVE-2023-36053",
              "shortDescription": {
                "text": "CVE-2023-36053 Package: pkg:pypi/django@3.0.7"
              },
              "help": {
                "text": "Vulnerability CVE-2023-36053\nCVSSv2: None\nCVSSv3: 7.5 High\nPackage: pkg:pypi/django@3.0.7\nFixed Version: \n",
                "markdown": "**Vulnerability CVE-2023-36053**\n| CVSSv2 | CVSSv3 | Package | Fixed Version |\n| --- | --- | --- | --- |\n|None|7.5 High|pkg:pypi/django@3.0.7||\n"
              },
              "properties": {
                "tags": [
                  "vulnerability",
                  "[None] [7.5 High]",
                  "pkg:pypi/django@3.0.7"
                ],
                "precision": "very-high"
              }
            },
            {
              "id": "[None] [7.5 High] CVE-2023-41164",
              "shortDescription": {
                "text": "CVE-2023-41164 Package: pkg:pypi/django@3.0.7"
              },
              "help": {
                "text": "Vulnerability CVE-2023-41164\nCVSSv2: None\nCVSSv3: 7.5 High\nPackage: pkg:pypi/django@3.0.7\nFixed Version: \n",
                "markdown": "**Vulnerability CVE-2023-41164**\n| CVSSv2 | CVSSv3 | Package | Fixed Version |\n| --- | --- | --- | --- |\n|None|7.5 High|pkg:pypi/django@3.0.7||\n"
              },
              "properties": {
                "tags": [
                  "vulnerability",
                  "[None] [7.5 High]",
                  "pkg:pypi/django@3.0.7"
                ],
                "precision": "very-high"
              }
            },
            {
              "id": "[None] [7.5 High] CVE-2023-43665",
              "shortDescription": {
                "text": "CVE-2023-43665 Package: pkg:pypi/django@3.0.7"
              },
              "help": {
                "text": "Vulnerability CVE-2023-43665\nCVSSv2: None\nCVSSv3: 7.5 High\nPackage: pkg:pypi/django@3.0.7\nFixed Version: \n",
                "markdown": "**Vulnerability CVE-2023-43665**\n| CVSSv2 | CVSSv3 | Package | Fixed Version |\n| --- | --- | --- | --- |\n|None|7.5 High|pkg:pypi/django@3.0.7||\n"
              },
              "properties": {
                "tags": [
                  "vulnerability",
                  "[None] [7.5 High]",
                  "pkg:pypi/django@3.0.7"
                ],
                "precision": "very-high"
              }
            },
            {
              "id": "[None] [7.5 High] CVE-2023-46695",
              "shortDescription": {
                "text": "CVE-2023-46695 Package: pkg:pypi/django@3.0.7"
              },
              "help": {
                "text": "Vulnerability CVE-2023-46695\nCVSSv2: None\nCVSSv3: 7.5 High\nPackage: pkg:pypi/django@3.0.7\nFixed Version: \n",
                "markdown": "**Vulnerability CVE-2023-46695**\n| CVSSv2 | CVSSv3 | Package | Fixed Version |\n| --- | --- | --- | --- |\n|None|7.5 High|pkg:pypi/django@3.0.7||\n"
              },
              "properties": {
                "tags": [
                  "vulnerability",
                  "[None] [7.5 High]",
                  "pkg:pypi/django@3.0.7"
                ],
                "precision": "very-high"
              }
            },
            {
              "id": "[7.5 High] [7.3 High] CVE-2021-44420",
              "shortDescription": {
                "text": "CVE-2021-44420 Package: pkg:pypi/django@3.0.7"
              },
              "help": {
                "text": "Vulnerability CVE-2021-44420\nCVSSv2: 7.5 High\nCVSSv3: 7.3 High\nPackage: pkg:pypi/django@3.0.7\nFixed Version: 3.1.14\n",
                "markdown": "**Vulnerability CVE-2021-44420**\n| CVSSv2 | CVSSv3 | Package | Fixed Version |\n| --- | --- | --- | --- |\n|7.5 High|7.3 High|pkg:pypi/django@3.0.7|3.1.14|\n"
              },
              "properties": {
                "tags": [
                  "vulnerability",
                  "[7.5 High] [7.3 High]",
                  "pkg:pypi/django@3.0.7"
                ],
                "precision": "very-high"
              }
            },
            {
              "id": "[4.3 Medium] [6.1 Medium] CVE-2021-32052",
              "shortDescription": {
                "text": "CVE-2021-32052 Package: pkg:pypi/django@3.0.7"
              },
              "help": {
                "text": "Vulnerability CVE-2021-32052\nCVSSv2: 4.3 Medium\nCVSSv3: 6.1 Medium\nPackage: pkg:pypi/django@3.0.7\nFixed Version: \n",
                "markdown": "**Vulnerability CVE-2021-32052**\n| CVSSv2 | CVSSv3 | Package | Fixed Version |\n| --- | --- | --- | --- |\n|4.3 Medium|6.1 Medium|pkg:pypi/django@3.0.7||\n"
              },
              "properties": {
                "tags": [
                  "vulnerability",
                  "[4.3 Medium] [6.1 Medium]",
                  "pkg:pypi/django@3.0.7"
                ],
                "precision": "very-high"
              }
            },
            {
              "id": "[4.3 Medium] [6.1 Medium] CVE-2022-22818",
              "shortDescription": {
                "text": "CVE-2022-22818 Package: pkg:pypi/django@3.0.7"
              },
              "help": {
                "text": "Vulnerability CVE-2022-22818\nCVSSv2: 4.3 Medium\nCVSSv3: 6.1 Medium\nPackage: pkg:pypi/django@3.0.7\nFixed Version: \n",
                "markdown": "**Vulnerability CVE-2022-22818**\n| CVSSv2 | CVSSv3 | Package | Fixed Version |\n| --- | --- | --- | --- |\n|4.3 Medium|6.1 Medium|pkg:pypi/django@3.0.7||\n"
              },
              "properties": {
                "tags": [
                  "vulnerability",
                  "[4.3 Medium] [6.1 Medium]",
                  "pkg:pypi/django@3.0.7"
                ],
                "precision": "very-high"
              }
            },
            {
              "id": "[5.0 Medium] [5.3 Medium] CVE-2021-3281",
              "shortDescription": {
                "text": "CVE-2021-3281 Package: pkg:pypi/django@3.0.7"
              },
              "help": {
                "text": "Vulnerability CVE-2021-3281\nCVSSv2: 5.0 Medium\nCVSSv3: 5.3 Medium\nPackage: pkg:pypi/django@3.0.7\nFixed Version: 3.1.6\n",
                "markdown": "**Vulnerability CVE-2021-3281**\n| CVSSv2 | CVSSv3 | Package | Fixed Version |\n| --- | --- | --- | --- |\n|5.0 Medium|5.3 Medium|pkg:pypi/django@3.0.7|3.1.6|\n"
              },
              "properties": {
                "tags": [
                  "vulnerability",
                  "[5.0 Medium] [5.3 Medium]",
                  "pkg:pypi/django@3.0.7"
                ],
                "precision": "very-high"
              }
            },
            {
              "id": "[5.0 Medium] [5.3 Medium] CVE-2021-28658",
              "shortDescription": {
                "text": "CVE-2021-28658 Package: pkg:pypi/django@3.0.7"
              },
              "help": {
                "text": "Vulnerability CVE-2021-28658\nCVSSv2: 5.0 Medium\nCVSSv3: 5.3 Medium\nPackage: pkg:pypi/django@3.0.7\nFixed Version: 3.1.8\n",
                "markdown": "**Vulnerability CVE-2021-28658**\n| CVSSv2 | CVSSv3 | Package | Fixed Version |\n| --- | --- | --- | --- |\n|5.0 Medium|5.3 Medium|pkg:pypi/django@3.0.7|3.1.8|\n"
              },
              "properties": {
                "tags": [
                  "vulnerability",
                  "[5.0 Medium] [5.3 Medium]",
                  "pkg:pypi/django@3.0.7"
                ],
                "precision": "very-high"
              }
            },
            {
              "id": "[5.0 Medium] [5.3 Medium] CVE-2021-45452",
              "shortDescription": {
                "text": "CVE-2021-45452 Package: pkg:pypi/django@3.0.7"
              },
              "help": {
                "text": "Vulnerability CVE-2021-45452\nCVSSv2: 5.0 Medium\nCVSSv3: 5.3 Medium\nPackage: pkg:pypi/django@3.0.7\nFixed Version: \n",
                "markdown": "**Vulnerability CVE-2021-45452**\n| CVSSv2 | CVSSv3 | Package | Fixed Version |\n| --- | --- | --- | --- |\n|5.0 Medium|5.3 Medium|pkg:pypi/django@3.0.7||\n"
              },
              "properties": {
                "tags": [
                  "vulnerability",
                  "[5.0 Medium] [5.3 Medium]",
                  "pkg:pypi/django@3.0.7"
                ],
                "precision": "very-high"
              }
            },
            {
              "id": "[4.0 Medium] [4.9 Medium] CVE-2021-33203",
              "shortDescription": {
                "text": "CVE-2021-33203 Package: pkg:pypi/django@3.0.7"
              },
              "help": {
                "text": "Vulnerability CVE-2021-33203\nCVSSv2: 4.0 Medium\nCVSSv3: 4.9 Medium\nPackage: pkg:pypi/django@3.0.7\nFixed Version: 3.1.12\n",
                "markdown": "**Vulnerability CVE-2021-33203**\n| CVSSv2 | CVSSv3 | Package | Fixed Version |\n| --- | --- | --- | --- |\n|4.0 Medium|4.9 Medium|pkg:pypi/django@3.0.7|3.1.12|\n"
              },
              "properties": {
                "tags": [
                  "vulnerability",
                  "[4.0 Medium] [4.9 Medium]",
                  "pkg:pypi/django@3.0.7"
                ],
                "precision": "very-high"
              }
            },
            {
              "id": "[None] [Medium] CVE-2024-24680",
              "shortDescription": {
                "text": "CVE-2024-24680 Package: pkg:pypi/django@3.0.7"
              },
              "help": {
                "text": "Vulnerability CVE-2024-24680\nCVSSv2: None\nCVSSv3: Medium\nPackage: pkg:pypi/django@3.0.7\nFixed Version: 3.2.24\n",
                "markdown": "**Vulnerability CVE-2024-24680**\n| CVSSv2 | CVSSv3 | Package | Fixed Version |\n| --- | --- | --- | --- |\n|None|Medium|pkg:pypi/django@3.0.7|3.2.24|\n"
              },
              "properties": {
                "tags": [
                  "vulnerability",
                  "[None] [Medium]",
                  "pkg:pypi/django@3.0.7"
                ],
                "precision": "very-high"
              }
            }]
        }
      },
      "results": [
        {
          "ruleId": "[7.5 High 9.8 Critical] CVE-2022-28346",
          "ruleIndex": 0,
          "level": "error",
          "message": {
            "text": "An issue was discovered in Django 2.2 before 2.2.28, 3.2 before 3.2.13, and 4.0 before 4.0.4. QuerySet.annotate(), aggregate(), and extra() methods are subject to SQL injection in column aliases via a crafted dictionary (with dictionary expansion) as the passed **kwargs."
          },
          "locations": [{
            "physicalLocation": {
              "artifactLocation": {
                "uri": "Dockerfile"
              },
              "region": {
                "startLine": 1,
                "startColumn": 1,
                "endColumn": 1
              }
            }
          }]
        },
        {
          "ruleId": "[7.5 High 9.8 Critical] CVE-2022-28347",
          "ruleIndex": 1,
          "level": "error",
          "message": {
            "text": "A SQL injection issue was discovered in QuerySet.explain() in Django 2.2 before 2.2.28, 3.2 before 3.2.13, and 4.0 before 4.0.4. This occurs by passing a crafted dictionary (with dictionary expansion) as the **options argument, and placing the injection payload in an option name."
          },
          "locations": [{
            "physicalLocation": {
              "artifactLocation": {
                "uri": "Dockerfile"
              },
              "region": {
                "startLine": 1,
                "startColumn": 1,
                "endColumn": 1
              }
            }
          }]
        },
        {
          "ruleId": "[7.5 High 9.8 Critical] CVE-2021-35042",
          "ruleIndex": 2,
          "level": "error",
          "message": {
            "text": "Django 3.1.x before 3.1.13 and 3.2.x before 3.2.5 allows QuerySet.order_by SQL injection if order_by is untrusted input from a client of a web application."
          },
          "locations": [{
            "physicalLocation": {
              "artifactLocation": {
                "uri": "Dockerfile"
              },
              "region": {
                "startLine": 1,
                "startColumn": 1,
                "endColumn": 1
              }
            }
          }]
        },
        {
          "ruleId": "[7.5 High 9.8 Critical] CVE-2022-34265",
          "ruleIndex": 3,
          "level": "error",
          "message": {
            "text": "An issue was discovered in Django 3.2 before 3.2.14 and 4.0 before 4.0.6. The Trunc() and Extract() database functions are subject to SQL injection if untrusted data is used as a kind/lookup_name value. Applications that constrain the lookup name and kind choice to a known safe list are unaffected."
          },
          "locations": [{
            "physicalLocation": {
              "artifactLocation": {
                "uri": "Dockerfile"
              },
              "region": {
                "startLine": 1,
                "startColumn": 1,
                "endColumn": 1
              }
            }
          }]
        },
        {
          "ruleId": "[None 9.8 Critical] CVE-2023-31047",
          "ruleIndex": 4,
          "level": "error",
          "message": {
            "text": "In Django 3.2 before 3.2.19, 4.x before 4.1.9, and 4.2 before 4.2.1, it was possible to bypass validation when using one form field to upload multiple files. This multiple upload has never been supported by forms.FileField or forms.ImageField (only the last uploaded file was validated). However, Django&#39;s &#34;Uploading multiple files&#34; documentation suggested otherwise."
          },
          "locations": [{
            "physicalLocation": {
              "artifactLocation": {
                "uri": "Dockerfile"
              },
              "region": {
                "startLine": 1,
                "startColumn": 1,
                "endColumn": 1
              }
            }
          }]
        },
        {
          "ruleId": "[None 8.8 High] CVE-2022-36359",
          "ruleIndex": 5,
          "level": "error",
          "message": {
            "text": "An issue was discovered in the HTTP FileResponse class in Django 3.2 before 3.2.15 and 4.0 before 4.0.7. An application is vulnerable to a reflected file download (RFD) attack that sets the Content-Disposition header of a FileResponse when the filename is derived from user-supplied input."
          },
          "locations": [{
            "physicalLocation": {
              "artifactLocation": {
                "uri": "Dockerfile"
              },
              "region": {
                "startLine": 1,
                "startColumn": 1,
                "endColumn": 1
              }
            }
          }]
        },
        {
          "ruleId": "[5.0 Medium 7.5 High] CVE-2020-29651",
          "ruleIndex": 6,
          "level": "error",
          "message": {
            "text": "A denial of service via regular expression in the py.path.svnwc component of py (aka python-py) through 1.9.0 could be used by attackers to cause a compute-time denial of service attack by supplying malicious input to the blame functionality."
          },
          "locations": [{
            "physicalLocation": {
              "artifactLocation": {
                "uri": "Dockerfile"
              },
              "region": {
                "startLine": 1,
                "startColumn": 1,
                "endColumn": 1
              }
            }
          }]
        },
        {
          "ruleId": "[5.0 Medium 7.5 High] CVE-2020-24583",
          "ruleIndex": 7,
          "level": "error",
          "message": {
            "text": "An issue was discovered in Django 2.2 before 2.2.16, 3.0 before 3.0.10, and 3.1 before 3.1.1 (when Python 3.7+ is used). FILE_UPLOAD_DIRECTORY_PERMISSIONS mode was not applied to intermediate-level directories created in the process of uploading files. It was also not applied to intermediate-level collected static directories when using the collectstatic management command."
          },
          "locations": [{
            "physicalLocation": {
              "artifactLocation": {
                "uri": "Dockerfile"
              },
              "region": {
                "startLine": 1,
                "startColumn": 1,
                "endColumn": 1
              }
            }
          }]
        },
        {
          "ruleId": "[5.0 Medium 7.5 High] CVE-2020-24584",
          "ruleIndex": 8,
          "level": "error",
          "message": {
            "text": "An issue was discovered in Django 2.2 before 2.2.16, 3.0 before 3.0.10, and 3.1 before 3.1.1 (when Python 3.7+ is used). The intermediate-level directories of the filesystem cache had the system&#39;s standard umask rather than 0o077."
          },
          "locations": [{
            "physicalLocation": {
              "artifactLocation": {
                "uri": "Dockerfile"
              },
              "region": {
                "startLine": 1,
                "startColumn": 1,
                "endColumn": 1
              }
            }
          }]
        },
        {
          "ruleId": "[5.0 Medium 7.5 High] CVE-2021-33571",
          "ruleIndex": 9,
          "level": "error",
          "message": {
            "text": "In Django 2.2 before 2.2.24, 3.x before 3.1.12, and 3.2 before 3.2.4, URLValidator, validate_ipv4_address, and validate_ipv46_address do not prohibit leading zero characters in octal literals. This may allow a bypass of access control that is based on IP addresses. (validate_ipv4_address and validate_ipv46_address are unaffected with Python 3.9.5+..) ."
          },
          "locations": [{
            "physicalLocation": {
              "artifactLocation": {
                "uri": "Dockerfile"
              },
              "region": {
                "startLine": 1,
                "startColumn": 1,
                "endColumn": 1
              }
            }
          }]
        },
        {
          "ruleId": "[5.0 Medium 7.5 High] CVE-2021-31542",
          "ruleIndex": 10,
          "level": "error",
          "message": {
            "text": "In Django 2.2 before 2.2.21, 3.1 before 3.1.9, and 3.2 before 3.2.1, MultiPartParser, UploadedFile, and FieldFile allowed directory traversal via uploaded files with suitably crafted file names."
          },
          "locations": [{
            "physicalLocation": {
              "artifactLocation": {
                "uri": "Dockerfile"
              },
              "region": {
                "startLine": 1,
                "startColumn": 1,
                "endColumn": 1
              }
            }
          }]
        },
        {
          "ruleId": "[5.0 Medium 7.5 High] CVE-2021-45115",
          "ruleIndex": 11,
          "level": "error",
          "message": {
            "text": "An issue was discovered in Django 2.2 before 2.2.26, 3.2 before 3.2.11, and 4.0 before 4.0.1. UserAttributeSimilarityValidator incurred significant overhead in evaluating a submitted password that was artificially large in relation to the comparison values. In a situation where access to user registration was unrestricted, this provided a potential vector for a denial-of-service attack."
          },
          "locations": [{
            "physicalLocation": {
              "artifactLocation": {
                "uri": "Dockerfile"
              },
              "region": {
                "startLine": 1,
                "startColumn": 1,
                "endColumn": 1
              }
            }
          }]
        },
        {
          "ruleId": "[5.0 Medium 7.5 High] CVE-2021-45116",
          "ruleIndex": 12,
          "level": "error",
          "message": {
            "text": "An issue was discovered in Django 2.2 before 2.2.26, 3.2 before 3.2.11, and 4.0 before 4.0.1. Due to leveraging the Django Template Language&#39;s variable resolution logic, the dictsort template filter was potentially vulnerable to information disclosure, or an unintended method call, if passed a suitably crafted key."
          },
          "locations": [{
            "physicalLocation": {
              "artifactLocation": {
                "uri": "Dockerfile"
              },
              "region": {
                "startLine": 1,
                "startColumn": 1,
                "endColumn": 1
              }
            }
          }]
        },
        {
          "ruleId": "[5.0 Medium 7.5 High] CVE-2022-23833",
          "ruleIndex": 13,
          "level": "error",
          "message": {
            "text": "An issue was discovered in MultiPartParser in Django 2.2 before 2.2.27, 3.2 before 3.2.12, and 4.0 before 4.0.2. Passing certain inputs to multipart forms could result in an infinite loop when parsing files."
          },
          "locations": [{
            "physicalLocation": {
              "artifactLocation": {
                "uri": "Dockerfile"
              },
              "region": {
                "startLine": 1,
                "startColumn": 1,
                "endColumn": 1
              }
            }
          }]
        },
        {
          "ruleId": "[5.0 None 7.5 High] CVE-2023-30608",
          "ruleIndex": 14,
          "level": "error",
          "message": {
            "text": "sqlparse is a non-validating SQL parser module for Python. In affected versions the SQL parser contains a regular expression that is vulnerable to ReDoS (Regular Expression Denial of Service). This issue was introduced by commit `e75e358`. The vulnerability may lead to Denial of Service (DoS). This issues has been fixed in sqlparse 0.4.4 by commit `c457abd5f`. Users are advised to upgrade. There are no known workarounds for this issue.\n."
          },
          "locations": [{
            "physicalLocation": {
              "artifactLocation": {
                "uri": "Dockerfile"
              },
              "region": {
                "startLine": 1,
                "startColumn": 1,
                "endColumn": 1
              }
            }
          }]
        },
        {
          "ruleId": "[5.0 None 7.5 High] CVE-2022-42969",
          "ruleIndex": 15,
          "level": "error",
          "message": {
            "text": "The py library through 1.11.0 for Python allows remote attackers to conduct a ReDoS (Regular expression Denial of Service) attack via a Subversion repository with crafted info data, because the InfoSvnCommand argument is mishandled."
          },
          "locations": [{
            "physicalLocation": {
              "artifactLocation": {
                "uri": "Dockerfile"
              },
              "region": {
                "startLine": 1,
                "startColumn": 1,
                "endColumn": 1
              }
            }
          }]
        },
        {
          "ruleId": "[None 7.5 High] CVE-2022-41323",
          "ruleIndex": 16,
          "level": "error",
          "message": {
            "text": "In Django 3.2 before 3.2.16, 4.0 before 4.0.8, and 4.1 before 4.1.2, internationalized URLs were subject to a potential denial of service attack via the locale parameter, which is treated as a regular expression."
          },
          "locations": [{
            "physicalLocation": {
              "artifactLocation": {
                "uri": "Dockerfile"
              },
              "region": {
                "startLine": 1,
                "startColumn": 1,
                "endColumn": 1
              }
            }
          }]
        },
        {
          "ruleId": "[None 7.5 High] CVE-2023-23969",
          "ruleIndex": 17,
          "level": "error",
          "message": {
            "text": "In Django 3.2 before 3.2.17, 4.0 before 4.0.9, and 4.1 before 4.1.6, the parsed values of Accept-Language headers are cached in order to avoid repetitive parsing. This leads to a potential denial-of-service vector via excessive memory usage if the raw value of Accept-Language headers is very large."
          },
          "locations": [{
            "physicalLocation": {
              "artifactLocation": {
                "uri": "Dockerfile"
              },
              "region": {
                "startLine": 1,
                "startColumn": 1,
                "endColumn": 1
              }
            }
          }]
        },
        {
          "ruleId": "[None 7.5 High] CVE-2023-24580",
          "ruleIndex": 18,
          "level": "error",
          "message": {
            "text": "An issue was discovered in the Multipart Request Parser in Django 3.2 before 3.2.18, 4.0 before 4.0.10, and 4.1 before 4.1.7. Passing certain inputs (e.g., an excessive number of parts) to multipart forms could result in too many open files or memory exhaustion, and provided a potential vector for a denial-of-service attack."
          },
          "locations": [{
            "physicalLocation": {
              "artifactLocation": {
                "uri": "Dockerfile"
              },
              "region": {
                "startLine": 1,
                "startColumn": 1,
                "endColumn": 1
              }
            }
          }]
        },
        {
          "ruleId": "[None 7.5 High] CVE-2023-36053",
          "ruleIndex": 19,
          "level": "error",
          "message": {
            "text": "In Django 3.2 before 3.2.20, 4 before 4.1.10, and 4.2 before 4.2.3, EmailValidator and URLValidator are subject to a potential ReDoS (regular expression denial of service) attack via a very large number of domain name labels of emails and URLs."
          },
          "locations": [{
            "physicalLocation": {
              "artifactLocation": {
                "uri": "Dockerfile"
              },
              "region": {
                "startLine": 1,
                "startColumn": 1,
                "endColumn": 1
              }
            }
          }]
        },
        {
          "ruleId": "[None 7.5 High] CVE-2023-41164",
          "ruleIndex": 20,
          "level": "error",
          "message": {
            "text": "In Django 3.2 before 3.2.21, 4.1 before 4.1.11, and 4.2 before 4.2.5, django.utils.encoding.uri_to_iri() is subject to a potential DoS (denial of service) attack via certain inputs with a very large number of Unicode characters."
          },
          "locations": [{
            "physicalLocation": {
              "artifactLocation": {
                "uri": "Dockerfile"
              },
              "region": {
                "startLine": 1,
                "startColumn": 1,
                "endColumn": 1
              }
            }
          }]
        },
        {
          "ruleId": "[None 7.5 High] CVE-2023-43665",
          "ruleIndex": 21,
          "level": "error",
          "message": {
            "text": "In Django 3.2 before 3.2.22, 4.1 before 4.1.12, and 4.2 before 4.2.6, the django.utils.text.Truncator chars() and words() methods (when used with html=True) are subject to a potential DoS (denial of service) attack via certain inputs with very long, potentially malformed HTML text. The chars() and words() methods are used to implement the truncatechars_html and truncatewords_html template filters, which are thus also vulnerable. NOTE: this issue exists because of an incomplete fix for CVE-2019-14232."
          },
          "locations": [{
            "physicalLocation": {
              "artifactLocation": {
                "uri": "Dockerfile"
              },
              "region": {
                "startLine": 1,
                "startColumn": 1,
                "endColumn": 1
              }
            }
          }]
        },
        {
          "ruleId": "[None 7.5 High] CVE-2023-46695",
          "ruleIndex": 22,
          "level": "error",
          "message": {
            "text": "An issue was discovered in Django 3.2 before 3.2.23, 4.1 before 4.1.13, and 4.2 before 4.2.7. The NFKC normalization is slow on Windows. As a consequence, django.contrib.auth.forms.UsernameField is subject to a potential DoS (denial of service) attack via certain inputs with a very large number of Unicode characters."
          },
          "locations": [{
            "physicalLocation": {
              "artifactLocation": {
                "uri": "Dockerfile"
              },
              "region": {
                "startLine": 1,
                "startColumn": 1,
                "endColumn": 1
              }
            }
          }]
        },
        {
          "ruleId": "[7.5 High 7.3 High] CVE-2021-44420",
          "ruleIndex": 23,
          "level": "error",
          "message": {
            "text": "In Django 2.2 before 2.2.25, 3.1 before 3.1.14, and 3.2 before 3.2.10, HTTP requests for URLs with trailing newlines could bypass upstream access control based on URL paths."
          },
          "locations": [{
            "physicalLocation": {
              "artifactLocation": {
                "uri": "Dockerfile"
              },
              "region": {
                "startLine": 1,
                "startColumn": 1,
                "endColumn": 1
              }
            }
          }]
        },
        {
          "ruleId": "[4.3 Medium 6.1 Medium] CVE-2021-32052",
          "ruleIndex": 24,
          "level": "error",
          "message": {
            "text": "In Django 2.2 before 2.2.22, 3.1 before 3.1.10, and 3.2 before 3.2.2 (with Python 3.9.5+), URLValidator does not prohibit newlines and tabs (unless the URLField form field is used). If an application uses values with newlines in an HTTP response, header injection can occur. Django itself is unaffected because HttpResponse prohibits newlines in HTTP headers."
          },
          "locations": [{
            "physicalLocation": {
              "artifactLocation": {
                "uri": "Dockerfile"
              },
              "region": {
                "startLine": 1,
                "startColumn": 1,
                "endColumn": 1
              }
            }
          }]
        },
        {
          "ruleId": "[4.3 Medium 6.1 Medium] CVE-2022-22818",
          "ruleIndex": 25,
          "level": "error",
          "message": {
            "text": "The {% debug %} template tag in Django 2.2 before 2.2.27, 3.2 before 3.2.12, and 4.0 before 4.0.2 does not properly encode the current context. This may lead to XSS."
          },
          "locations": [{
            "physicalLocation": {
              "artifactLocation": {
                "uri": "Dockerfile"
              },
              "region": {
                "startLine": 1,
                "startColumn": 1,
                "endColumn": 1
              }
            }
          }]
        },
        {
          "ruleId": "[5.0 Medium 5.3 Medium] CVE-2021-3281",
          "ruleIndex": 26,
          "level": "error",
          "message": {
            "text": "In Django 2.2 before 2.2.18, 3.0 before 3.0.12, and 3.1 before 3.1.6, the django.utils.archive.extract method (used by &#34;startapp --template&#34; and &#34;startproject --template&#34;) allows directory traversal via an archive with absolute paths or relative paths with dot segments."
          },
          "locations": [{
            "physicalLocation": {
              "artifactLocation": {
                "uri": "Dockerfile"
              },
              "region": {
                "startLine": 1,
                "startColumn": 1,
                "endColumn": 1
              }
            }
          }]
        },
        {
          "ruleId": "[5.0 Medium 5.3 Medium] CVE-2021-28658",
          "ruleIndex": 27,
          "level": "error",
          "message": {
            "text": "In Django 2.2 before 2.2.20, 3.0 before 3.0.14, and 3.1 before 3.1.8, MultiPartParser allowed directory traversal via uploaded files with suitably crafted file names. Built-in upload handlers were not affected by this vulnerability."
          },
          "locations": [{
            "physicalLocation": {
              "artifactLocation": {
                "uri": "Dockerfile"
              },
              "region": {
                "startLine": 1,
                "startColumn": 1,
                "endColumn": 1
              }
            }
          }]
        },
        {
          "ruleId": "[5.0 Medium 5.3 Medium] CVE-2021-45452",
          "ruleIndex": 28,
          "level": "error",
          "message": {
            "text": "Storage.save in Django 2.2 before 2.2.26, 3.2 before 3.2.11, and 4.0 before 4.0.1 allows directory traversal if crafted filenames are directly passed to it."
          },
          "locations": [{
            "physicalLocation": {
              "artifactLocation": {
                "uri": "Dockerfile"
              },
              "region": {
                "startLine": 1,
                "startColumn": 1,
                "endColumn": 1
              }
            }
          }]
        },
        {
          "ruleId": "[4.0 Medium 4.9 Medium] CVE-2021-33203",
          "ruleIndex": 29,
          "level": "error",
          "message": {
            "text": "Django before 2.2.24, 3.x before 3.1.12, and 3.2.x before 3.2.4 has a potential directory traversal via django.contrib.admindocs. Staff members could use the TemplateDetailView view to check the existence of arbitrary files. Additionally, if (and only if) the default admindocs templates have been customized by application developers to also show file contents, then not only the existence but also the file contents would have been exposed. In other words, there is directory traversal outside of the template root directories."
          },
          "locations": [{
            "physicalLocation": {
              "artifactLocation": {
                "uri": "Dockerfile"
              },
              "region": {
                "startLine": 1,
                "startColumn": 1,
                "endColumn": 1
              }
            }
          }]
        },
        {
          "ruleId": "[None Medium] CVE-2024-24680",
          "ruleIndex": 30,
          "level": "error",
          "message": {
            "text": "An issue was discovered in Django 3.2 before 3.2.24, 4.2 before 4.2.10, and Django 5.0 before 5.0.2. The intcomma template filter was subject to a potential denial-of-service attack when used with very long strings."
          },
          "locations": [{
            "physicalLocation": {
              "artifactLocation": {
                "uri": "Dockerfile"
              },
              "region": {
                "startLine": 1,
                "startColumn": 1,
                "endColumn": 1
              }
            }
          }]
        }],
      "columnKind": "utf16CodeUnits"
    }
  ]
}
